apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  containers:
    - name: myapp
      image: ttl.sh/anakarla99-harbour:2h        # ← el pipeline sobreescribe esto con la tag real
      ports:
        - containerPort: 4444
      livenessProbe:
        httpGet:
          path: /
          port: 4444
        initialDelaySeconds: 5
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /
          port: 4444
        initialDelaySeconds: 3
        periodSeconds: 5
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "200m"