apiVersion: v1
kind: Pod
metadata:
  labels:
    run: myapp
  name: myapp
spec:
  containers:
  - image: ttl.sh/alejandro-ramirez:2h
    name: myapp
    ports:
    - containerPort: 4444
    
    livenessProbe:
      httpGet:
        path: /
        port: 4444
    readinessProbe:
      httpGet:
        path: /
        port: 4444

    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "250m"